services:
  # Backend API Service
  - type: web
    name: sameer-portfolio-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://sameer-portfolio-frontend.onrender.com
      - key: ABUSE_DETECTION_ENABLED
        value: true
      - key: MAX_REQUESTS_PER_MINUTE
        value: 60
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
    healthCheckPath: /api/chat/health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: sameer-portfolio-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://sameer-portfolio-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 